[package]
name = "gfx2inc"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.2"

[build-dependencies]
anyhow = "1.0"
vergen = { version = "6", default-features = false, features = ["build", "git"] }
